# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bb_in_relative_coords": "01_BBox_utils.ipynb",
         "BBFormats": "01_BBox_utils.ipynb",
         "BBox": "01_BBox_utils.ipynb",
         "read_xml_anns": "01_BBox_utils.ipynb",
         "draw_bbs": "01_BBox_utils.ipynb",
         "area": "01_BBox_utils.ipynb",
         "load_image": "02_inference.ipynb",
         "get_n_best_bbs": "02_inference.ipynb",
         "get_bbs": "02_inference.ipynb",
         "plot": "02_inference.ipynb",
         "get_bb_crop": "02_inference.ipynb",
         "get_bb_crops": "02_inference.ipynb",
         "get_foods_and_recipes": "02_inference.ipynb"}

modules = ["bbox.py",
           "inference.py",
           "None.py"]

doc_url = "https://ThesisSlayers.github.io/two_stage_detector/"

git_url = "https://github.com/ThesisSlayers/two_stage_detector/tree/main/"

def custom_doc_links(name): return None
